version: '3'

services:
  web:
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
  sass:
    image: larryprice/sass
    volumes:
      - ./public/styles:/src
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DAT23ABASE: l23423423ocalhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./database:/var/lib/mysql
    depends_on:
      - web
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
